/// Returns the human-readable name for a monster type.
pub fn get_monster_type_name(type_: i32) -> &'static str {
    match type_ {
        0 => "NPC",
        1 => "Monster",
        2 => "Chest",
        3 => "Switch",
        4 => "Trap",
        5 => "Harvest",
        6 => "Critter",
        7 => "Travel",
        _ => "Unknown",
    }
}

/// Returns the human-readable field name for a given monster type and field ID.
/// Based on the overrides in MonsterNPC, MonsterMonster, MonsterCritter,
/// MonsterHarvest, MonsterSwitch, MonsterTrap, and MonsterCategory.
pub fn get_monster_field_name(monster_type: i32, field_id: i32) -> &'static str {
    match monster_type {
        0 => match field_id {
            0 => "Armor",
            1 => "Helm",
            2 => "Boots",
            3 => "Gloves",
            4 => "Sex",
            5 => "Ancestry",
            6 => "Eye Color",
            7 => "Hair",
            8 => "Hair Color",
            9 => "Beard",
            10 => "Beard Color",
            11 => "Eyebrow Color",
            12 => "Boss Form",
            _ => "Unknown Field",
        },
        1 => match field_id {
            0 => "HP",
            1 => "Attack Power",
            2 => "Phys Def",
            3 => "Fire Def",
            4 => "Cold Def",
            5 => "Poison Def",
            6 => "Light Def",
            7 => "Dark Def",
            8 => "AI",
            9 => "Run speed",
            10 => "Anim|Idle",
            11 => "Anim|Runstart",
            12 => "Anim|Runend",
            13 => "Anim|Run",
            14 => "Anim|Attack",
            15 => "Anim|Strong",
            16 => "Anim|Special",
            17 => "Stamina",
            18 => "Vox Jab",
            19 => "Vox Fierce",
            20 => "Vox Hit",
            21 => "Vox Die",
            22 => "Vox Laugh",
            23 => "Vox Scream",
            24 => "Vox Growl",
            25 => "Phase Thresh",
            26 => "Craze Thresh",
            27 => "-Attack Min:",
            28 => "-Attack Max:",
            29 => "-Attack Vert:",
            30 => "-Attack Cooldown:",
            31 => "-Strong Min:",
            32 => "-Strong Max:",
            33 => "-Strong Vert:",
            34 => "-Strong Cooldown:",
            35 => "-Special Min:",
            36 => "-Special Max:",
            37 => "-Special Vert:",
            38 => "-Special Cooldown:",
            39 => "Poise",
            40 => "Snd Step",
            41 => "Poise Atk",
            42 => "Hover Speed",
            43 => "Hover Accel",
            44 => "Summoner",
            45 => "Loot 1 Type",
            46 => "Loot 1 Prob",
            47 => "Loot 1 Count",
            48 => "Loot 2 Type",
            49 => "Loot 2 Prob",
            50 => "Loot 2 Count",
            51 => "Loot 3 Type",
            52 => "Loot 3 Prob",
            53 => "Loot 3 Count",
            54 => "Loot 4 Type",
            55 => "Loot 4 Prob",
            56 => "Loot 4 Count",
            57 => "Loot 5 Type",
            58 => "Loot 5 Prob",
            59 => "Loot 5 Count",
            60 => "Shield Time",
            61 => "Shield Cooldown",
            62 => "XP:",
            63 => "Area:",
            64 => "Riposte Dist",
            65 => "Dodge Cooldown",
            66 => "Dodge Window",
            67 => "Linked Monster",
            _ => "Unknown Field",
        },
        2 => match field_id {
            _ => "Unknown Field",
        },
        3 => match field_id {
            0 => "Req Mage Kills",
            _ => "Unknown Field",
        },
        4 => match field_id {
            0 => "Attack Power",
            1 => "Poise Atk",
            _ => "Unknown Field",
        },
        5 => match field_id {
            0 => "Loot 1 Type",
            1 => "Loot 1 Prob",
            2 => "Loot 1 Count",
            3 => "Loot 2 Type",
            4 => "Loot 2 Prob",
            5 => "Loot 2 Count",
            6 => "Loot 3 Type",
            7 => "Loot 3 Prob",
            8 => "Loot 3 Count",
            9 => "Loot 4 Type",
            10 => "Loot 4 Prob",
            11 => "Loot 4 Count",
            12 => "Loot 5 Type",
            13 => "Loot 5 Prob",
            14 => "Loot 5 Count",
            15 => "Associated Monster",
            _ => "Unknown Field",
        },
        6 => match field_id {
            0 => "Snd Step",
            1 => "Boss Form",
            _ => "Unknown Field",
        },
        7 => "Unknown Field", // no fields
        _ => "Unknown Field",
    }
}

/// Returns the human-readable flag name for a given monster type and index.
pub fn get_monster_flag_name(monster_type: i32, flag_idx: i32) -> &'static str {
    match monster_type {
        0 => match flag_idx {
            0 => "Intro Guard",
            1 => "Hazeburnt",
            2 => "No Turn",
            _ => "Unknown Flag",
        },
        1 => match flag_idx {
            0 => "Mage",
            1 => "Mob",
            2 => "Minion",
            3 => "Hover",
            4 => "Giant",
            5 => "Elem|Fire",
            6 => "Elem|Water",
            7 => "Elem|Lit",
            8 => "Elem|Poison",
            9 => "Elem|Earth",
            10 => "Elem|Time",
            11 => "Elem|Flesh",
            12 => "Elem|Fungus",
            13 => "Elem|Mech",
            14 => "Elem|Demon",
            15 => "Elem|Dragon",
            16 => "Elem|Books",
            17 => "Elem|Air",
            18 => "Elem|Ice",
            19 => "Elem|Force",
            20 => "Elem|Divine",
            21 => "Elem|Light",
            22 => "Elem|Blood",
            23 => "Elem|Undead",
            24 => "Elem|Mind",
            25 => "Elem|Dark",
            26 => "Elite Minion",
            27 => "Special Minion",
            28 => "Can Leap",
            29 => "Can Warp",
            30 => "Hazeburnt",
            31 => "Refract Wraith",
            32 => "Elem|Red Lit",
            33 => "Elem|Red Fire",
            34 => "Boss",
            35 => "Elem|Mummy",
            36 => "Undead",
            37 => "Elem|Hag",
            38 => "Shadow",
            39 => "Prism",
            40 => "Treeheart",
            41 => "Treeghost",
            42 => "Elem|Ghost",
            43 => "Mimic",
            44 => "Elem|Blue Dragon",
            45 => "Symbiotic Boss",
            46 => "Elem|Sky",
            47 => "Devourable",
            48 => "Elem|Messiah",
            49 => "Phantom Rect",
            50 => "Elem|Owl",
            51 => "Elem|Sky/Lit",
            52 => "Beam Buff",
            53 => "Long Death",
            54 => "Elem|Heart",
            55 => "Elem|Protect",
            56 => "Can Grapple Atk",
            57 => "Elem|Sheriff",
            58 => "Elem|Oath",
            59 => "Elem|Shroud",
            60 => "Elem|Hunger",
            61 => "Elem|Blueheart",
            62 => "Elem|Dawnlight",
            63 => "Facing Invis",
            64 => "Dummy",
            65 => "Minimal Height",
            66 => "Can Fall Off",
            67 => "Elem|Healpot",
            68 => "No Boss Col",
            69 => "Mask Arms",
            70 => "Mask 1",
            71 => "Mask 2",
            72 => "Mask 3",
            73 => "Mask 4",
            74 => "Elem|Traitor",
            75 => "Die Tier Big",
            76 => "Smooth Hover Rope",
            77 => "Elem|Gold",
            _ => "Unknown Flag",
        },
        2 => "Unknown Flag",
        3 => match flag_idx {
            0 => "Checkpoint",
            1 => "Give Item",
            2 => "Stone Circle",
            3 => "Fire Door",
            4 => "Sky Door",
            5 => "Arena Check",
            6 => "Main Check",
            7 => "Arena Check Return",
            _ => "Unknown Flag",
        },
        4 => match flag_idx {
            0 => "Tripwire",
            1 => "Fixed Pos",
            2 => "Fungal",
            3 => "Mechano",
            4 => "Stone Circle",
            5 => "Friendly to Monsters",
            6 => "Mask Lasers",
            _ => "Unknown Flag",
        },
        5 => match flag_idx {
            0 => "Hazeburnt",
            1 => "Mage Clue",
            2 => "Side Clue",
            _ => "Unknown Flag",
        },
        6 => match flag_idx {
            0 => "Can Pet",
            1 => "Flies Away",
            2 => "Wretch",
            3 => "Talking Tree",
            4 => "Hazeburnt",
            5 => "Divine Tree",
            6 => "Watcher",
            7 => "Hover",
            8 => "No Turn",
            9 => "Ambient",
            10 => "Candelabra",
            _ => "Unknown Flag",
        },
        7 => match flag_idx {
            0 => "Start Point",
            1 => "End Point",
            _ => "Unknown Flag",
        },
        _ => "Unknown Flag",
    }
}